clashapi responses and first get
noahkohrs/riot-api-java-kotlin pull request #20
Opened 2024-09-09 16:49 UTC by DNSJambon

2024-09-09 18:41 UTC, DNSJambon commented
ktlint format OK

2024-09-09 18:42 UTC, DNSJambon commented
command works but checks fails

2024-09-10 15:55 UTC, DNSJambon commented on riot-api/src/main/kotlin/com.noahkohrs.riot.api/account/Responses.kt
is it ok?

2024-09-11 11:11 UTC, noahkohrs requested changes

2024-09-11 11:11 UTC, noahkohrs commented on riot-api/src/main/kotlin/com.noahkohrs.riot.api/lol/clash/ClashApi.kt
> +// TODO: Generate a test for this class by right-clicked on <ClassName> -> Generate -> Test... -> OK
nit: Should be removed.

2024-09-11 11:11 UTC, noahkohrs commented on riot-api/src/main/kotlin/com.noahkohrs.riot.api/account/Responses.kt
I would rather removing the account test than exposing the constructor

2024-09-11 12:40 UTC, noahkohrs commented
Also mark the endpoint as done in the `README.md` checklist 🫡​

2024-09-11 13:39 UTC, DNSJambon commented
not ready, probelm

2024-09-11 15:54 UTC, merged